### ISSUE TITLE
Tablist Prefix an/ausschalten

### ISSUE THREAD

**Issue by Cautex** [Floxiii/Lobby#3]
Lieber Floxii, ich hätte gerne, dass man das Tablist Prewfix ausschalten kann. Das Chat Prefix kann man ja bereits auschalten. Es würde mich freuen, dass bei dem 3.0 Release zu sehen.
Daneke

**Comment by Floxiii** [comment]
Hey, wird es bei der 3.0 geben. Derzeit geht es auch musst nur 'Scoreboard' auf false setzen.
